# .streamlit/secrets.toml
# Place this file in the .streamlit/ folder in your project root

[gcp_service_account]
type = "service_account"
project_id = "elevated-apex-360403"
private_key_id = "fe2360a19bc6b56ef458c243bc94345450a14041"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCz0oRzecmB5u/F
rKe8Ok+M4w0OWEG/rahf8NXrw9PEANHadQM4s0C7f614WabdHOwxdkK3+J66tC4j
BU6Bw1aCXaR413x8MzY7CBByub3euiGs1ch+SK0I4D9HdRZk8BvPFFa7ILDO4R4/
EdKfR/Uh0xai4hKe0U6aIh6T2HU8Rr0TFGiyko5C2DtG+5zLztBQG1TbL1gzDXS3
8GY0vYjPzAOwgwHSBDVtgEZNSyr61PdHxW0KgdUCS+fds3YJlNQblmvys4jYWwzc
rCMC8SBHEMaYhRCx8R0yeeFMpIBv24UlDpmXlg9BXlUU4l+OVsYTR2IYvGxBMqef
d/sWoxmfAgMBAAECggEATl4tNiw56yCLl3Ee6tPYznQ3QOyqvs/+ZM2PVUATXsTi
sBu1yzSnve8vWRdtNsj/kLDS891ow8J5pu6Nn9TTM15/KuDykig5drGVhYI4YsRo
n6vNxGeE7azZNxmqqFPSMsXQ5J2jII4QgfkQ+zS/er3FjDgNWGSsplS/UbyQnzMT
9iZX4sH7/saKnah994GDAnKgEsKhMuBomddvtUakRzrbTbItnZNj+4mBdGMdzzY0
SuVgO9B7k+DQ5vbrZS07DPjywAJ4/SgyV9+ea7iSpB5Ug25QV7jqR6gv5OrWyKSh
VnAL1FEjlRRjTt+/NP9PLPO9wNvrkWqLMKJv/Y47wQKBgQDY/xO2epNlfbbw8OwR
SsI28XsvjnjsPtNQtvpYQxv7MstI+pSIYxEDBJ1Xf94LPIsqvSNOug5d7bTm0D2/
9OcYv+nAlABViDgpfHGWg0bAoKe8Fj7u2GjNe3YeoA9RtPrDLUgb4hrRQTwgwSmq
Cagw58suyddfAokNRXO9HXmSwQKBgQDUJOeIKtlXc7xUsPaytEztX09es1IMco6I
dck6v6LbWNibDElt4vo6Wy1vLp3+XcA80AdXma2Alkl+OXT0gzJ7hoSn9JH7r9Dc
u8z7J32uJ//RQArlo8Krkp7JOIRsl/Q2WUywWzEXW8uQPvQX7BEd/U2vOzbz7g+K
G96i3wKkXwKBgAnXJ3GzBVQo607p3gq6tSwAr3FsqJcuEi8q3Rd7k51EpGte0bWN
qIvWfbwmFE+2IymBAkTjsxsXWIjPEL3PwVsh+Nu+2nUGhGV9Ozl0IpVBs9mXuKrk
LXyECMtCvu8ZofWP7CE3k7fBmZRyrg0D+xicql4o0ReB6e0sJR+CYq0BAoGAGcXq
AxcBlKhQ5xEgx5E0D1qW7/BlNXHtcxKsQeDqTi+7EQsrGJiMwe411N4a/74wDrNP
UQswkwCvKRCd7t7JkUxEbYs++Q7hFxAR1Sl1EWV2pNtc940vp1yGwfeFzxOe7cNn
l71cd3QFhR7A1O8vHS+a8oEFKhlv9d1w7OSfE40CgYEAoISxwLqMZMNrMYwqp3u2
IKWHPqhOHhJP27sEHmQg0PIt0n5IppRD/BgepqWwMuY32CN0DHAxEe49v2PcdkIz
Bsq58ImXUfAGfbbI3IS029r2bPtHkJeJSYvgBEQbdtDSxSpDuzDEl7t95W1Xt7aV
8fqEMV6Nz1z1FvMH2+9h+04=
-----END PRIVATE KEY-----"""
client_email = "masterdata-950@elevated-apex-360403.iam.gserviceaccount.com"
client_id = "109484565593844446221"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/masterdata-950%40elevated-apex-360403.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# Optional: You can also store the sheet URL and worksheet name here
[app_config]
sheet_url = "https://docs.google.com/spreadsheets/d/10_bnGF7WBZ0J3aSvl8riufNbZjXAxB7wcnN3545fGzw/edit?gid=1081628845#gid=1081628845"
worksheet_name = "Farm details"